SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2
  RESTORE_FROM: /data/project_frb/SegDA/compareDAseg/ADVENT/domain_adaptation/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
TEST:
  MODE: best